version: "3.6"

services:
    db:
        container_name: iproj_db
        build:
            context: .
            dockerfile: .docker/mssql/dockerfile
        restart: always
        ports:
            - "1433:1433"
